- docs/_static/css/risk_table.css
- docs/conf.py
- docs/risk_assessment.rst
This address #52. There was a typo, which has now been fixed.
> Fixed colors in risk table

- .github/workflows/ci_cron_weekly.yml
- .github/workflows/ci_tests.yml
- .readthedocs.yml
- docs/conf.py
- m4opt/models/background/zodiacal.py
- pyproject.toml
- setup.cfg
- tox.ini
Numpy has dropped support for it.
> Drop support for Python 3.8

- m4opt/models/background/zodiacal.py
- setup.cfg
- Warn that it is only valid near Earth.
- Add plots.
> Add more documentation for zodiacal light background

- m4opt/models/background/skybright/__init__.py
The data file doesn't contain any units, so thre is no benefit to using QTable.read.
> Use numpy.loadtxt, not QTable.read here

- m4opt/models/background/skybright/__init__.py
- Remove docstring from undocumented read_kpno_sky_data. It's not visible in the Sphinx docs, and most of its contents was repeated.
- Add a pretty plot.
> Rework SkyBackground docs

- docs/solvers.rst
This PR adds details to the documentation for academic users installing CPLEX onto an HPC cluster like SDSC Expanse.
> Add CPLEX installation details for HPC resources

- m4opt/models/math.py
> Unwrap Numpy scalars as Python scalars

- m4opt/conftest.py
- setup.cfg
- tox.ini
See https://github.com/astropy/astropy/issues/15095.
> Only run doctests for Numpy >= 2.0.0

- .github/workflows/ci_tests.yml
See https://github.com/codecov/codecov-action/issues/1293.
> Downgrade codecov

- pyproject.toml
See https://github.com/pypa/setuptools_scm/blob/main/README.md.
> Update build-system.requires to latest recommendation

- .pre-commit-config.yaml
- pyproject.toml
> Revert "Work around bug in progressbar2"

- m4opt/models/_extinction.py
The ESA site has been down all day.
> Use IRSA dust map mirror by default

- m4opt/_cli/schedule.py
> Fix output of zero-length schedules

- m4opt/_cli/schedule.py
- m4opt/missions/__init__.py
- m4opt/missions/_ultrasat.py
This PR adds the initial configuration setup for the ULTRASAT mission, with some parameters currently using some  default values from the UVEX mission. These default values will be replaced in future updates to accurately reflect ULTRASAT's background noise environment, which is dominated by **Zodiacal light**, **Cerenkov radiation**, and **Stray light**. This setup creates the foundation for ULTRASAT's mission configuration, with further refinements planned.
> Ultrasat mission config

- m4opt/_cli/animate.py
Since astropy 7.0.0, quantity support can be used as a decorator. We no longer need our own decorator.
> Use Astropy's quantity_support decorator

- m4opt/conftest.py
> Always enable pytest-astropy-header

- docs/design/milp.rst
- m4opt/_cli/schedule.py
The symmetry is useful for the adaptive exposure time formulation.
> Use midpoint time, not start time, as decision variable

- docs/design/milp.rst
- m4opt/_cli/schedule.py
> Disallow zero-duration exposures

- m4opt/constraints/__init__.py
- m4opt/constraints/_altitude.py
This PR adds the AltitudeConstraint to limit the Field of Regard  based on altitude.
> Add AltitudeConstraint to limit FoR

- m4opt/constraints/__init__.py
- m4opt/constraints/_airmass.py
This PR adds a Field of Regard (FoR) constraint using AirmassConstraint to ensure observations are limited based on airmass values.
> Implement AirmassConstraint for FoR limitation

- m4opt/constraints/__init__.py
- m4opt/constraints/_atnight.py
This PR adds the AtNightConstraint to restrict observations to nighttime conditions.
> AtNightConstraint for nighttime observations

- m4opt/constraints/_airmass.py
- m4opt/constraints/_altitude.py
- Both classes now support passing the minimum and maximum in any order.
- The airmass constraint now supports both float and quantity input.
> Refactor airmass and altitude constraints

- docs/refs.bib
- m4opt/dynamics/__init__.py
- m4opt/dynamics/_slew.py
- m4opt/missions/_ultrasat.py
- m4opt/missions/_uvex.py
- Introduce a Slew base class to make room for future addition of more sophisticated slew models.
- Clear up confusion about the optimal slew trajectory. We have modeled an eigenaxis maneuver, which is _not_ the optimal maneuver in general.
> Add slew base class, clear up confusion about optimal slew

- docs/conf.py
- m4opt/synphot/__init__.py
- m4opt/synphot/_bandpass.py
- pyproject.toml
We can use this to filter transmission curves for LSST, ZTF, etc.
> Add function to get bandpass from SVO filter profile service

- m4opt/constraints/__init__.py
- m4opt/constraints/_logical.py
> Add logical constraints

- .github/workflows/ci_cron_weekly.yml
- .github/workflows/ci_tests.yml
- .github/workflows/codeql-analysis.yml
See https://www.cisa.gov/news-events/alerts/2025/03/18/supply-chain-compromise-third-party-tj-actionschanged-files-cve-2025-30066-and-reviewdogaction
> Pin GitHub Actions to sha hashes

- pyproject.toml
See https://github.com/fastapi/typer/discussions/1215#discussioncomment-13151851.
> Remove click pin

- m4opt/_cli/schedule.py
- pyproject.toml
This was fixed in astropy 7.1.0.
> Remove workaround for astropy/astropy#17717

- m4opt/_cli/animate.py
- m4opt/_cli/schedule.py
- m4opt/constraints/_core.py
- m4opt/constraints/_logical.py
- m4opt/missions/_core.py
- m4opt/missions/_ultrasat/__init__.py
- m4opt/missions/_uvex.py
This simplifies evaluating a mission's constraints because you don't have to loop over them yourself.
> Overload logical operators on constraints
